- name: Install glexec package
  package:
    name: glexec-wn
    state: latest

- name: Configure glexec.conf
  template:
    src: templates/glexec.conf.j2
    dest: /etc/glexec.conf
    owner: root
    group: glexec
    mode: 0640

- name: Configure glexec.conf
  template:
    src: templates/lcmaps-glexec.db.j2
    dest: /etc/lcmaps/lcmaps-glexec.db
    owner: root
    group: root
    mode: 0640
