- src: https://github.com/egi-qc/ansible-umd
  version: master
  name: umd

- src: https://github.com/egi-qc/ansible-grid-security
  version: master
  name: grid-security

- src: grycap.munge
  name: munge
