# This task assumes that cvmfs role is already installed

# Mount home from sbgce1.in2p3.fr to /home through autofs

# Install nfs-utils
- name: Install nfs-utils
  yum:
    name: nfs-utils
    state: latest

# Create directory /grid-mnt
- name: Create directory /grid-mnt
  file:
    path: /grid-mnt
    state: directory
    owner: root
    group: root
    mode: 0755

# Remove /home directory and create a symlink from /home to /grid-mnt/home
# First check if /home exists as a directory
- name: Check status of /home
  stat:
    path: /home
  register: home_check

# If it does, remove it
- name: Remove /home
  file:
    path: /home
    state: absent
  when: home_check.stat.isdir is defined and home_check.stat.isdir is true  

# Create symlink from /home to /grid-mnt/home
- name: Create symlink from /home to /grid-mnt/home
  file:
    path: '/home'
    state: link
    src: '/grid-mnt/home'
    force: yes

# Create symlink for sessiondir
# First create top level directory for sessiondir
- name: Create directory for sessiondir
  file:
    path: '{{ arc_frontend_sessiondir | dirname }}'
    state: directory
    
- name: Create symlink for sessiondir
  file:
    path: '{{ arc_frontend_sessiondir }}'
    state: link
    src: '/grid-mnt/{{ arc_frontend_sessiondir | basename }}'
    force: yes


# Mount sbgce1.in2p3.fr:/home to /home FIXME: generalize
# FIXME: also includes sessiondir
# Configure autofs
- name: Configure autofs /etc/auto.home
  template:
    src: 'templates/auto.home.j2'
    dest: '/etc/auto.home'
    owner: root
    group: root
    mode: 0644

- name: Configure autofs /etc/auto.master.d/home.autofs
  template:
    src: 'templates/home.autofs.j2'
    dest: '/etc/auto.master.d/home.autofs'
    owner: root
    group: root
    mode: 0644

# Restart autofs
- name: Restart autofs
  service:
    name: 'autofs'
    state: restarted

