- name: Install wn packages
  dnf:
    name: '{{ wn_rpm_packages }}'
    state: latest


# FIXME: I think that should be done way earlier than in wn role
#- name: Configure Autofs
#  include_tasks: autofs.yml

#- name: Deploy glexec
#  include_tasks: glexec.yml
#  when: deploy_glexec

#- include: slurm.yaml
#  when: deploy_slurm
